# Generated by Django 5.0.2 on 2024-08-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FieldRequest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
