# Generated by Django 5.0.2 on 2024-08-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldRequest', '0002_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetails',
            name='s_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='FieldRequest.studentdetails'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentdetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
